"""Collect experiment outputs into final tables used by the report."""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
REPORT = ROOT / "report"
REPORT.mkdir(parents=True, exist_ok=True)


def read_json(name: str, required: bool = True):
    path = RESULTS / name
    if not path.exists():
        if required:
            raise FileNotFoundError(f"Missing required result: {path}")
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def fmt(value) -> str:
    return "--" if value is None else f"{float(value):.4f}"


def tex_escape(text: str) -> str:
    replacements = {
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in str(text))


def main() -> None:
    baseline = read_json("baseline_results.json")
    task1 = read_json("task1_results.json")
    task2 = read_json("task2_results.json")
    task3 = read_json("task3_results.json")
    task4 = read_json("task4_results.json")
    split_audit = read_json("data_split_audit.json")
    gtzan_preprocessing = read_json("gtzan_preprocessing.json")
    mtat_preprocessing = read_json("mtat_preprocessing.json")

    # Model, accuracy, Macro-F1, mean AUC-PR, Recall@5. A dash is used only
    # where a metric does not apply to that task.
    rows = []
    random_mtat = baseline["mtat_19_target_tags"]["models"]["uniform_random"]
    rows.append(["Random tags (MTAT)", None, random_mtat["macro_f1"], random_mtat["mean_auc_pr"], None])
    task1_metrics = task1["test_metrics"]
    rows.append(["Task 1: DistilBERT", None, task1_metrics["macro_f1"], task1_metrics["mean_auc_pr"], None])
    rows.append([
        "Task 2: GraphSAGE", task2["gnn"]["test_metrics"]["accuracy"],
        task2["gnn"]["test_metrics"]["macro_f1"], None, None,
    ])
    rows.append([
        "Task 2: CNN", task2["cnn"]["test_metrics"]["accuracy"],
        task2["cnn"]["test_metrics"]["macro_f1"], None, None,
    ])
    for mode, label in [
        ("bert_only", "Task 3: BERT only"),
        ("gnn_only", "Task 3: GNN only"),
        ("concat", "Task 3: Concatenation"),
        ("cross_attention", "Task 3: Cross-attention"),
    ]:
        metrics = task3["results"][mode]["test_metrics"]
        rows.append([label, None, metrics["macro_f1"], metrics["mean_auc_pr"], None])
    rows.append([
        "Task 4: Contrastive",
        None,
        None,
        None,
        task4["caption_to_audio"]["R@5"],
    ])

    with (RESULTS / "faculty_evaluation_table.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["Model", "Accuracy", "Macro-F1", "AUC-PR", "R@5"])
        writer.writerows(rows)

    markdown = [
        "| Model | Accuracy | Macro-F1 | AUC-PR | R@5 |",
        "|---|---:|---:|---:|---:|",
    ]
    for model, accuracy, macro_f1, auc_pr, recall5 in rows:
        markdown.append(
            f"| {model} | {fmt(accuracy)} | {fmt(macro_f1)} | {fmt(auc_pr)} | {fmt(recall5)} |"
        )
    (RESULTS / "faculty_evaluation_table.md").write_text("\n".join(markdown) + "\n", encoding="utf-8")

    consolidated = {
        "data_split_audit": split_audit,
        "preprocessing": {"gtzan": gtzan_preprocessing, "mtat": mtat_preprocessing},
        "baselines": baseline,
        "task1": task1,
        "task2": task2,
        "task3": task3,
        "task4": task4,
    }
    (RESULTS / "metrics.json").write_text(
        json.dumps(consolidated, indent=2, allow_nan=False), encoding="utf-8"
    )

    table_rows = "\n".join(
        f"{tex_escape(model)} & {fmt(accuracy)} & {fmt(macro_f1)} & {fmt(auc_pr)} & {fmt(recall5)} \\\\" 
        for model, accuracy, macro_f1, auc_pr, recall5 in rows
    )
    example_rows = []
    for example in task1["examples"][:3]:
        caption = example["caption"].strip()
        if len(caption) > 115:
            caption = caption[:112].rstrip() + "..."
        true_tags = ", ".join(example["true_tags_in_vocabulary"][:4]) or "none in vocabulary"
        predicted_tags = ", ".join(
            item["tag"] for item in example["top_5_predictions"][:4]
        )
        example_rows.append(
            f"{tex_escape(caption)} & {tex_escape(true_tags)} & {tex_escape(predicted_tags)} \\\\"
        )
    example_table_rows = "\n".join(example_rows)
    generated = rf"""
% This file is generated by scripts/generate_report_assets.py.
\newcommand{{\TaskOneMacro}}{{{task1_metrics['macro_f1']:.4f}}}
\newcommand{{\TaskOneMicro}}{{{task1_metrics['micro_f1']:.4f}}}
\newcommand{{\TaskOneAUC}}{{{task1_metrics['mean_auc_pr']:.4f}}}
  \newcommand{{\TaskTwoGNNFone}}{{{task2['gnn']['test_metrics']['macro_f1']:.4f}}}
  \newcommand{{\TaskTwoCNNFone}}{{{task2['cnn']['test_metrics']['macro_f1']:.4f}}}
  \newcommand{{\TaskTwoGNNAccuracy}}{{{task2['gnn']['test_metrics']['accuracy']:.4f}}}
  \newcommand{{\TaskTwoCNNAccuracy}}{{{task2['cnn']['test_metrics']['accuracy']:.4f}}}
\newcommand{{\TaskThreeCrossFone}}{{{task3['results']['cross_attention']['test_metrics']['macro_f1']:.4f}}}
\newcommand{{\TaskThreeCrossAUC}}{{{task3['results']['cross_attention']['test_metrics']['mean_auc_pr']:.4f}}}
\newcommand{{\TaskThreeConcatFone}}{{{task3['results']['concat']['test_metrics']['macro_f1']:.4f}}}
\newcommand{{\TaskThreeConcatAUC}}{{{task3['results']['concat']['test_metrics']['mean_auc_pr']:.4f}}}
\newcommand{{\MusicCapsTrain}}{{{task1['split_counts']['train']}}}
\newcommand{{\MusicCapsValidation}}{{{task1['split_counts']['val']}}}
\newcommand{{\MusicCapsTest}}{{{task1['split_counts']['test']}}}
\newcommand{{\MTATTrain}}{{{task3['split_counts']['train']}}}
\newcommand{{\MTATValidation}}{{{task3['split_counts']['val']}}}
\newcommand{{\MTATTest}}{{{task3['split_counts']['test']}}}
\newcommand{{\TaskFourTrain}}{{{task4['split_counts']['train']}}}
\newcommand{{\TaskFourValidation}}{{{task4['split_counts']['val']}}}
\newcommand{{\TaskFourTest}}{{{task4['split_counts']['test']}}}
\newcommand{{\TaskFourCtoAOne}}{{{task4['caption_to_audio']['R@1']:.4f}}}
\newcommand{{\TaskFourCtoAFive}}{{{task4['caption_to_audio']['R@5']:.4f}}}
\newcommand{{\TaskFourCtoATen}}{{{task4['caption_to_audio']['R@10']:.4f}}}
\newcommand{{\TaskFourAtoCOne}}{{{task4['audio_to_caption']['R@1']:.4f}}}
\newcommand{{\TaskFourAtoCFive}}{{{task4['audio_to_caption']['R@5']:.4f}}}
\newcommand{{\TaskFourAtoCTen}}{{{task4['audio_to_caption']['R@10']:.4f}}}
\newcommand{{\TaskFourRandomFive}}{{{task4['random_retrieval_baseline']['caption_to_audio']['R@5']:.4f}}}
\newcommand{{\TaskFourBestEpoch}}{{{task4['best_epoch']}}}
\newcommand{{\TaskFourZeroShotMacro}}{{{task4['zero_shot_tag_transfer']['task4_caption_to_tag_prompt']['macro_f1']:.4f}}}
\newcommand{{\TaskFourTaskThreeMacro}}{{{task4['zero_shot_tag_transfer']['task3_cross_attention_direct_transfer']['macro_f1']:.4f}}}
  \newcommand{{\EvaluationTableRows}}{{%
{table_rows}
  }}
  \newcommand{{\TaskOneExampleRows}}{{%
{example_table_rows}
  }}
"""
    (REPORT / "generated_results.tex").write_text(generated.strip() + "\n", encoding="utf-8")
    print("Generated metrics.json, CSV/Markdown tables, and report/generated_results.tex")


if __name__ == "__main__":
    main()
